menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/710x710
    GitHub: https://github.com/710leo
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: 710leo
duoshuo: 

# Analytics
# google-analytics:
ga: UA-54783341-1

# Copyright Infomation
startyear: 2014

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
